# 🧠 NumPy Basics Lab

**Author**: Christian Theisen  
**Date**: June 2025  
**Description**: This notebook contains foundational practice with NumPy, including array creation, operations, reshaping, and broadcasting. Part of my AI/ML learning repo.

In [ ]:
import numpy as np

## 🧪 Section 1: Array Creation
Creating 1D and 2D arrays using `np.array()` to understand basic array structures.

In [3]:
print("Array Creation")
a = np.array([1, 2, 3])
print("1D Array:", a)

b = np.array([[1, 2], [3, 4]])
print("2D Array:\n", b)

Array Creation
1D Array: [1 2 3]
2D Array:
 [[1 2]
 [3 4]]


## 🧪 Section 2: Array Properties
Exploring array attributes like shape, size, and data type.

In [4]:
print("\nArray Properties")
print("Shape:", b.shape)
print("Size:", b.size)
print("Data Type:", b.dtype)


Array Properties
Shape: (2, 2)
Size: 4
Data Type: int64


## 🧪 Section 3: Indexing and Slicing
Accessing specific elements and rows using indexing and slicing techniques.

In [5]:
print("\nIndexing and Slicing")
print("First element of a:", a[0])
print("Second row of b:", b[1])
print("Element at row 1 col 0:", b[1, 0])


Indexing and Slicing
First element of a: 1
Second row of b: [3 4]
Element at row 1 col 0: 3


## 🧪 Section 4: Vectorized Operations
Using NumPy to perform fast element-wise operations without loops.

In [6]:
print("\nVectorized Operations")
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("x + y:", x + y)
print("x * y:", x * y)
print("x squared:", x ** 2)


Vectorized Operations
x + y: [5 7 9]
x * y: [ 4 10 18]
x squared: [1 4 9]


## 🧪 Section 5: Broadcasting
Demonstrating how NumPy handles operations between arrays of different shapes.

In [7]:
print("\nBroadcasting")
m = np.array([[1], [2], [3]])
n = np.array([10, 20, 30])
print("m + n:\n", m + n)


Broadcasting
m + n:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## 🧪 Section 6: Reshaping and Stacking
Changing array shapes and combining arrays vertically using `reshape()` and `vstack()`.

In [8]:
print("\nReshaping and Stacking")
c = np.arange(6)
print("Original:", c)

reshaped = c.reshape((2, 3))
print("Reshaped to 2x3:\n", reshaped)

d = np.array([[7, 8, 9]])
stacked = np.vstack([reshaped, d])
print("Stacked vertically:\n", stacked)


Reshaping and Stacking
Original: [0 1 2 3 4 5]
Reshaped to 2x3:
 [[0 1 2]
 [3 4 5]]
Stacked vertically:
 [[0 1 2]
 [3 4 5]
 [7 8 9]]


## 💡 Practice Exercise 1: Create Full Array
Create a 2D array of shape (3, 4) filled with the value 7 using `np.full()`.

In [9]:
a = np.full((3,4),7)
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


## 💡 Practice Exercise 2: Create Ranged Array
Use `np.arange()` to create a 1D array from 10 to 50 (inclusive) stepping by 5.

In [10]:
b = np.arange(10,51,5)
print(b)

[10 15 20 25 30 35 40 45 50]


## 💡 Practice Exercise 3: Reshape an Array
Generate a 1D array of 1–12, reshape it to (3, 4), and multiply all values by 10.

In [11]:
c = np.arange(1,13).reshape(3,4)
print("Original:\n",c)

# Multiply all values by 10
print("Multiplied:\n", c*10)

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Multiplied:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


## 💡 Practice Exercise 4: Generate Random Numbers
Generate 1,000 values from a standard normal distribution and calculate statistics.

In [12]:
r = np.random.normal(0, 1, 1000)

# Get mean, std, min, max
print("Mean:", np.mean(r))
print("Std Dev:", np.mean(r))
print("Min:", np.min(r), "Max:", np.max(r))

Mean: -0.035808235232163886
Std Dev: -0.035808235232163886
Min: -3.042690413229263 Max: 3.4295703931741235
